name: Deploy to production
on:
  push:
    branches: [main]
jobs:
  vercel:
    name: Deploy to Vercel
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Deploy to Vercel Action
        uses: BetaHuhn/deploy-to-vercel-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          GITHUB_DEPLOYMENT_ENV: preview
          PRODUCTION: false
          ALIAS_DOMAINS: ${{ steps.aliases.outputs.domain }}
          BUILD_ENV: |
            NEXT_PUBLIC_APP_ENV=production
            NEXT_PUBLIC_CHAIN=mainnet
            NEXT_PUBLIC_ALCHEMY_API_KEY=XWARo6CnMrqGv9ywk9NH_YULc2_o_Ny6
